### ISSUE TITLE
Streamline upload in predict-eth.md, via bundlr

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1000]
**Is your feature request related to a problem? Please describe.**

In predict-eth.md, sec 4.2 is to manually upload csv to GDrive, to get url 10 lines.

Aim of this issue: replace that with:
```python
import pybundlr
url = pybundlr.upload_file(file_name, alice_wallet)
```
With uploading ideal goals: (a) decentralized (b) permanent (c) tamper-proof (d) uses ETH/MATIC etc as payment

**How**

Leverage bundlr. Create a new library `pybundlr` that wraps part of [its CLI](https://docs.bundlr.network/docs/client/cli), to implement `upload_file()` above.

It meets the one-line goal, and the ideal goals (a)(b)(c)(d) too.

**TODOs**

- [x] Implement new repo: pybundlr. With unit test. Publish to pypi
- [ ] In ocean.py, update predict-eth.md with one-line upload
- [ ] Merge into main

**Describe alternatives you've considered**

Other options:
- IPFS + pinned node, or Filecoin. Benefits are like above, except not permanent
- encrypt predictions into an Ocean data NFT via ERC725, like the READMEs. Could make an ocean.py interface to make it simpler. This meets the goals above, but doesn't make it easy to share to >1 people (yet) or scale to storing lots of data (yet). Better to start with bundlr. Then we can address those two issues, eg via threshold cryptography and bundlr.

--

About new pybundlr package:
- github repo: https://github.com/oceanprotocol/pybundlr
- pypi package: https://pypi.org/project/pybundlr/ (set up via [this tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/))

More links:
- [arweave http api](https://docs.arweave.org/developers/server/http-api)
- [AR faucet](https://faucet.arweave.net/)

**Comment by trentmc** [comment]
Commit https://github.com/oceanprotocol/ocean.py/commit/f28e5001f11a3e565f167672cf605a1921d167c5 is also for this issue: make arweave mandatory, therefore guarantee tamper-proofness.
