### ISSUE TITLE
Improve ocean_assets::create() interface & implementation 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1094]
### Issues

- Confusion between "asset" and "ddo". Most of the code that uses an "asset" object is really just using a "ddo". We should call it as such, and let "asset" be a more general idea of the _union_ of (data nft, datatokens, ddo).
- Until recently, ocean_assets.create() didn't have good defaults for many of its args. It was super-hard to use. So, I built _create1(), which filled in good defaults, and on top of that, three even simpler methods: `create_url_asset()`, `create_graphql_asset()`, and `create_onchain_asset()`. Those have an even simpler interface and allowed us to nicely clean up the READMEs. Now, create() _does_ have more good defaults. And it is still often used directly. 
- However in create(), the developer still has to do a lot of work to set the needed values (metadata, services, etc).
- And now we have four methods for asset creation: the lower-level create() plus the three new higher-level ones.
- create()'s implementation is quite hard to read, partly because it's so long
- create()'s unit tests are kinda hard to navigate, and (it looks like) not thorough
- if someone wants to create an asset, it's usually just one datatoken, and they already know the pricing: free, or fixed-price with a price value. But right now, the work to set the price must be done after, and it's fairly involved too
- there are many unit tests that pass in 10+ args to create(). Most are boilerplate. This makes it hard to maintain tests.

### TODOs

- [x] clearer labeling: code uses "ddo" to mean ddo, and "asset" to mean union of (data nft, datatokens, ddo)
- [x] create() becomes as simple to use as the create_url_asset() etc, via even better use of good defaults, easy-to-read implementation, and easy-to-read unit tests
- [x] include: create() always returns a tuple (data nft, datatokens, ddo). Don't ever return just ddo
- [x] include: in tests for create(), usually just use good defaults, vs 10+ args
- [ ] create() lets the user optionally set a pricing scheme (free or fixed-price) with associated parameters
- [ ] deprecate create_url_asset(), because create() has becomes so good

### TODOs (added by Călina)
- [ ] throughout the tests, there are a lot of assets created that use the same defaults. Comb through all the usages and use a single test helper to publish. Remove duplicated usages.
- [ ] same goes for metadata in tests -> use a fixture instead; also check `url =` and other common links
