### ISSUE TITLE
Unskip test_issue981_consume.py, and fix remaining issues (if any)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1131]
### Background

In test module https://github.com/oceanprotocol/ocean.py/blob/main/tests/integration/ganache/test_issue981_consume.py ...

... its sole test is still skipped:
```python
@pytest.mark.skip(reason="Don't skip, once fixed #1013")
@pytest.mark.integration
def test1(
...
```

I just checked, [#1013](https://github.com/oceanprotocol/ocean.py/issues/1013) is fixed. 

### TODOs for this issue

- [x] Create a branch + PR. 
- [x] In it, unskip the issue. Verify that it passes. If it doesn't, fix as needed
- [ ] Merge in PR
