### ISSUE TITLE
Refactor example_config.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1147]
### Background

Config has become _way_ better in the last month or so, thanks to great work by @calina-c. 

Now, [`example_config.py`](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/example_config.py) has a few quick-win simplifications that will further help UX and maintenance.

### TODOs
- [ ] [`ExampleConfig`](https://github.com/oceanprotocol/ocean.py/blob/e5e640e855645a3d939649c2ef7c2c075e39e3c1/ocean_lib/example_config.py#L80), is now just a one-liner to `get_config_dict(network_name)`. So, deprecate `ExampleConfig` and replace calls to it (in READMEs etc) with calls to `get_config_dict().
- [ ] In `get_config_dict()`, rename `config_helper` to `config_dict`
- [ ] `CONFIG_NETWORK_HELPER` is currently a dict of dicts. But each inner dict always has just a single entry, so a dict isn't needed. Flatten to make it just one dictd. 
- [ ] Rename `CONFIG_NETWORK_HELPER` to something more precise, e.g. `PROVIDER_PER_NETWORK`
