### ISSUE TITLE
Streamline fixed-rate-exchange & marketplace README 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1149]
### Background

Status quo: marketplace-flow.md README currently needs 21 lines for Alice to set up a fixed-rate exchange (FRE), and for Bob to purchase.

Goal: change ocean.py such that FRE README such that it's 2-4 lines. Doing this _well_ means fully refactoring the FRE implementation.

This issue is a pre-requisite for: [#1095](https://github.com/oceanprotocol/ocean.py/issues/1095): "Streamline mean README flow"

###  TODOs

- [x] Create a first [branch](https://github.com/oceanprotocol/ocean.py/tree/issue1149-market-readme) and [PR](https://github.com/oceanprotocol/ocean.py/pull/1154)
  - write first-cut implementation & README
  - Replace using `FixedRateExchangeDetails` with `FixedRateExchangeStatus`, it will be far simpler. And similar for other `FixedRateExchange*` data-structure-like classes
  - Get test_fixed_rate_exchange.py working
- [x] Create a [second branch](https://github.com/oceanprotocol/ocean.py/tree/issue1149-market-2) and PR (FIXME). Use it from here on. 
- [x] Introduce new `OneExchange` class, which is `FixedRateExchange` but for just one `exchange_id`. Its interface is similar to that of `FixedRateExchange`, except: each method doesn't need `exchange_id` argument. 
   - [x] Write basic unit tests - drawing on first branch's basic tests
   - [x] Do first-cut implementation
   - [x] Get basic unit tests running
- [x] get all test_fixed_rate_exchange.py unit tests working
- [x] update the market README
- [x] get test_exchange_swap_fees.py unit tests working
- [ ] get remaining tests working
- [ ] get a review done. Merge.
- [ ] update Roberto's blog post pointing to df.md: ocean.create_fixed_rate() --> datatoken version
