### ISSUE TITLE
Expand CI to more OSes & Py versions

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1159]
### Background

We're now aiming to support Mac and Win better. And, we should always support the most recent version of Python; Python 3.11 just came out.

Current status: {build test, unit tests} x {Linux} x {Python 3.10}

Goal: {build test, unit tests} x {Linux, Mac, Win} x {Python 3.10, Python 3.11}

Q: for Mac, not just "Mac" but instead "pre-M1 Mac" and "M1 Mac" ?

### TODOs

- [x] add dependabot. PR: [#1157](https://github.com/oceanprotocol/ocean.py/pull/1157)
- [x] expand build tests to more OSes & Py versions. PR: [#1157](https://github.com/oceanprotocol/ocean.py/pull/1157)
- [x] fix failing CI test that the previous PR introduced. It fails on macOS * coincurve. [Example log]( https://github.com/oceanprotocol/ocean.py/actions/runs/3686236674/jobs/6238196875).
- [x] expand unit tests to more OSes & Py versions
  - [x] decide which unit tests to expand
  - [x] implement it
- [x] ensure that [installation README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/install.md) supports all three OSes

### Related

Issue [#1158](https://github.com/oceanprotocol/ocean.py/issues/1158) "ocean.py build fails on python 3.11 (all), python 3.10 (Mac)"

**Comment by AnaLoznianu** [comment]
For the installation readme, in the last step for setting the envvars we need:
* set ..... for windows 
* export ... for linux/macos
