### ISSUE TITLE
For action combos, minimize # txs by leveraging helper contract methods

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1166]
### Summary

We have some potentially low-hanging fruit to minimize # txs when doing (a) create_asset + post for free/priced, (b) download file, (c) maybe more. Via helper smart contract methods.

This issue is about doing that. But note that we have other things to do first. (See Priorities section.)

### Motivation

_Alex:_  (in slack)
I would have expected this [create exchange] in ocean_assets.create, since we have a lot of helpers in the contracts factory to reduce no of tx

_Trent:_

I agree to the value of that. We need to walk before we run.

The first priority has been to ensure that atomic actions -- atomic from perspective of user -- are clean.

And some of these naturally bundle. Examples:
- download_file() - does (1) do the order (2) do the download
- create() - could do (1) create data nft (2) create datatoken (3) create ddo (4) deploy a dispenser or fixed-price. Right now it does (1)(2)(3) but we could extend to (4) too.

With those natural bundles, we can then optimize the # txs by leveraging the special smart contracts calls. (And for cases we don't have that, use Gnosis Transaction Builder.)

But it's one step at a time. 

### TODOs

- [ ] Do bundle: `ocean_assets::create()` lets the user optionally set a pricing scheme (free or fixed-price) with associated parameters. Minimize # txs doing this
- [ ] Do bundle: in `download_file()`, minimize # txs when doing this. Must work for all combos of {free, priced} x {template 1, template 2}
- [ ] Identify other existing helper contract methods to identify opportunities. Add to this issue's TODOs to leverage them
- [ ] Look at flows in ocean.py and predict-eth READMEs, to find any other natural bundles. Identify them here, and add to this issue's TODOs to leverage them. If we don't have existing helper contract method for a highly-used bundle, add "try out Gnosis Transaction Builder" to the TODOs
- [ ] By the time we're here, we've added several TODOs. Prioritize them, and execute on them. For larger issues (eg Gnosis), perhaps create a new issue, then treat _this_ issue like an epic.
 
### On Priority

Priority of this issue: only do _after_ we've fixed bugs (there are currently >5 that really matter), and done other UX cleanups.

Recently-completed UX cleanups:
- [#977](https://github.com/oceanprotocol/ocean.py/issues/977) use brownie
- [#910](https://github.com/oceanprotocol/ocean.py/issues/910) Streamline dispenser.py & dispenser-flow README 
- [#1094](https://github.com/oceanprotocol/ocean.py/issues/1094) Improve ocean_assets::create() interface & implementation 

Other UX cleanups, that are higher priority than this, include:
- [#1194](https://github.com/oceanprotocol/ocean.py/issues/1194) Streamline fixed-rate-exchange & marketplace README #1149
- [#1095](https://github.com/oceanprotocol/ocean.py/issues/1095) Streamline main README flows; harmonize main local <> remote versions
- [#1165](https://github.com/oceanprotocol/ocean.py/issues/1165)  It's hard for py devs to see contract methods of DataNFT, Datatoken, etc

**Comment by calina-c** [comment]
There is a case to be made here regardint DispenserArguments and ExchangeArguments. When we are creating objects and their pricing schemas at once, we are in fact mirroring what we do in dt.create_exchange and dt.create_dispenser, with the same defaults. We could implement DispenserArguments and ExchangeArguments in the same way we implement DataNFTArguments, DatatokenArguments etc., for a seamless way of setting these defaults.

In addition, this would improve the architecture on _create_1dt. My goal is to transform what we now have as _create_1dt to accept an optional parameter for the pricing schema. Instead of creating two functions called `create_1dt_with_dispenser` and `create_1dt_with_fixed_rate`, we could pass in an argument e.g. `pricing_schema_params: Optional[DispenserArguments, ExchangeArguments] = None` and call the appropriate tx combo based on the instance of the pricing schema arguments. This simplification would also bubble up nicely to create_url_asset and its siblings.

**Comment by trentmc** [comment]
Data Nft Arguments and Datatoken arguments certainly helped in good defaults for lower level logic. But right now they are still a bit painful to use at the higher level: to create a simple data nft I have 

Before we go to "improve" more arguments with more data structures,

**Comment by trentmc** [comment]
DataNFTArguments and DatatokenArguments certainly helped wrt good defaults for lower level logic. 

But right now they are still a bit painful to use at the higher level: to create a simple data nft, I have to:
- import DataNFTArguments
- instantiate DataNFTArguments
- call nft factory "create". 

It's not super-painful, though, because at the higher level, people use ocean_assets.py. At some point, we can have to data nft factory "create" calls that use either DataNFTArguments OR simple good defaults to construct DataNFTArguments.

--

Given the above for data nfts and datatokens, I do *not* want to create more complicated interface for exchange and dispenser. If you want to create arguments objects for them, fine, but preserve the existing interface so that users do not have to import and instantiate separate "arguments" classes.

**Comment by trentmc** [comment]
Wrt priority of this issue: I see several other issues with higher priority. It would be good to do those first. These include:
- fix breaking tests, so that we can do CI of PRs in confidence 
- get #1260 merged. When I ran its PR tests last week, several failed due to the bullet above 
- do [pybundlr#7](https://github.com/oceanprotocol/pybundlr/issues). So that people in a python flow can upload files locally into arweave permanent storage, without npm issues 

There are more too. But the ones above are low hanging fruit.

**Comment by calina-c** [comment]
@trentmc 
- CIs are done and can work now with them.
- This issue was prioritised during one of the sprint plannings and the asset creation part is almost done.

I've added the arguments objects and I believe them to be very useful in the combo architecture. If you can review that PR, let me know if I should keep the former interface inside `create_datatoken` and `create_exchange`. I'm fine with reverting the changes I did for those interfaces. However, I think in combos it is an excellent choice and it fits the architecture and usability nicely.

**Comment by trentmc** [comment]
I assume the PR regarding exchange and dispenser args is this one:
https://github.com/oceanprotocol/ocean.py/pull/1297/files

The interface is much harder to use than before. It's asking the user to import another class, and construct another object. 

> let me know if I should keep the former interface inside create_datatoken and create_exchange.

Yes. Definitely.

And, like I suggested for DataNFTArguments class in the comment above, maybe we can have both:
- an easier interface, where the caller doesn't have to do the additional import and class instantiation. But, optionally, they can. 
- and under the hood it always uses an "arguments" class 

This pattern can be used in four places, to create:
- data nft 
- datatoken
- dispenser 
- exchange

**Comment by calina-c** [comment]
In essence, our issue is with the instantiation. I'll try to think of something smarter to "cover up" that instantiation. I think it's possible, but I need to think about it a bit.

**Comment by calina-c** [comment]
OK, I have options :)

### A) Using args/kwargs magic (tested)
Only for interfaces that take in ONE argument, not a combination, i.e. `create_datatoken`, `create_dispenser`, if we have the tx_dict first, we can do some magic with the arguments. I can use the `*args` and `**kwargs` magic to build the Arguments class automatically (where the arg/kwarg itself is of course NOT already an Argument class).

pros: beautiful, magical and elegant, will be compatible with the previous args and keyword args without instantiating an Argument class in the readmes
cons: I can not implement it for functions that take in multiple argument types, i.e. combos like create NFT + ERC20. There, the user will *have* to define the Argument objects separately

### Mapping argument groups to argument objects (not tested yet)
I can derive argument groups in the following ways:
1. either the user separates them in tuples (no need for the import, at least. We can build the Argument class based on the tuples, but under the hood)
2. some convention like prefixing (i.e. data_nft_symbol kwarg to be sent to DataNFTArgument object, datatoken_symbol to DatatokenArgument object)

pros: it would encompass the case for multiple argument groups given to the same function
cons: clunky and really weird to use in either case, I don't think dropping some imports is worth it. It also breaks the interfaces in a uglier way and I personally don't like it.

**Comment by trentmc** [comment]
### Option C

- **Don't** change dispenser and exchange creation. That is, preserve status quo. (One only has four parameters, the other only has two. So extra arguments class for each just to pass this around is pretty heavy, relatively speaking.)
- **Don't** bother creating better interfaces to create data nft and datatoken. That is, preserve status quo. Since we already have interfaces in ocean_assets.py.

**Comment by trentmc** [comment]
My analysis: options A and B add a lot of complexity. Option C doesn't add complexity, and already has good interfaces for users.

My choice is option C.


 I lean to option

**Comment by calina-c** [comment]
@trentmc Keeping C then. I've already started on reverting the interface changes and I'll let you know when you can re-review the changes.

In the meantime, here is my experimental commit for option A (just dataNFT changes as a PoC):
https://github.com/oceanprotocol/ocean.py/commit/5c943e91273cb99cd19630300db1dc8b25db1634

If you think we can circle back to this later, I'd be happy to implement this type of solution to make the interface more flexible. I agree it introduces some complexity, but I believe it's reasonable and clean.

**Comment by trentmc** [comment]
> If you think we can circle back to this later, I'd be happy to implement this type of solution to make the interface more flexible. I agree it introduces some complexity, but I believe it's reasonable and clean.

(I finally got a chance to sit at my desktop to look at this.)

I just took a look. 

It's surprisingly clean; cleaner than I expected possible. Great stuff!!!

Therefore I'm fine if you merge the PR (once past protoype phase). And I'm fine if you propagate that pattern to the other three places. (This includes changes to "exchange" and "dispenser".) Sorry if this felt like a flip-flop; at the end we all want a good interface with low-complexity code.
