### ISSUE TITLE
Revive models/tests/test_exchange_fees.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1176]
### Background

Github issue [#1149](https://github.com/oceanprotocol/ocean.py/issues/1149) was to streamline fixed_rate_exchange.py. This was done, in commit https://github.com/oceanprotocol/ocean.py/commit/4da2ade35660d92b39d75710387f57cceb8c3c87.
- It included: leveraging OO more for [models/fixed_rate_exchange.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/fixed_rate_exchange.py), to able to make the interface much cleaner.
- And a small tweak was: rename the test modules to [models/test/test_exchange_main.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/test/test_exchange_main.py) & [models/test/test_exchange_fees.py](https://github.com/oceanprotocol/ocean.py/blob/main/ocean_lib/models/test/test_exchange_fees.py).

However, I wasn't able to properly test and debug test_exchange_fees.py.
- I kept hitting [barge#339](https://github.com/oceanprotocol/barge/issues/339) "Upgrade to latest Ganache. Why: older Ganache has a bug which delays chain update on tx, which breaks unit tests"
- So I put a pytest.mark.skip() at its top

### TODO

- Pre-requisite: barge # 339 is done.
- [ ] Create a branch / PR. In the PR, revive test_exchange_fees.py. Un-skip the test. 
- [ ] Fix pytest fixture names. Including "datatoken" -> "DT", then inside the body have "dt = DT". And maybe more.
- [ ] Running locally, iterate on it until it passes. There may be other tweaks needed.
- [ ] Ensure remote CI passes. Merge

### Questions 

I found that when moving "test datatoken enterprise" to new clean exchange interface, it assumed 18 decimal places, and that was the only way that the test would work.

Is that perhaps also a similar thing here?

(Perhaps not, because at least some tests were passing when the delay was introduced)

**Comment by calina-c** [comment]
closed with https://github.com/oceanprotocol/ocean.py/pull/1193
