### ISSUE TITLE
Need basic support for *all* DF/VE contracts

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1235]
### Background / motivation

Issue [#916](https://github.com/oceanprotocol/ocean.py/issues/916) was "Expose VE & DF functionality into ocean.py". [Commit is here](https://github.com/oceanprotocol/ocean.py/commit/ce0f4db1b1da8e3b56e9e53071b4037266ef6edc).

But, it only exposed _some_ functionality.

Now I see that I need other functionality, such as DFRewards and DFStrategy1.

### Data: All DF/VE contracts, in `contracts` repo
- [DFRewards.sol](https://github.com/oceanprotocol/contracts/blob/main/contracts/df/DFRewards.sol)
- [DFStrategyV1.sol](https://github.com/oceanprotocol/contracts/blob/main/contracts/df/DFStrategyV1.sol)
- [SmartWalletChecker.sol](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/SmartWalletChecker.sol)
- [veAllocate.sol](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veAllocate.sol)
- [veDelegation.vy](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veDelegation.vy)
- [veDelegationProxy.vy](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veDelegationProxy.vy)
- [veFeeDistributor.vy](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veFeeDistributor.vy)
- [veFeeEstimate.vy](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veFeeEstimate.vy)
- [veOCEAN.vy](https://github.com/oceanprotocol/contracts/blob/main/contracts/ve/veOCEAN.vy)

### Data: DF/VE in ocean.py so far

Of the DF/VE contracts above, what's in ocean_lib/models/ (and ocean_lib/models/vetest/):
- veAllocate, in ve_allocate.py (and test_ve_allocate)
- veFeeDistributor, in ve_fee_distributor.py (and test)
- veOCEAN, in ve_ocean.py (and test)

### TODO: High-level

Expose the rest of the functionality. It can be super-basic, the same way that previous DF/VE contracts were exposed. Like this:
```python
class VeOcean(ContractBase):
    CONTRACT_NAME = "veOCEAN"
```

And, have tests. They can be super-basic too: just test for existence.

### TODO: Specific

- [ ] First, rename `vetest/` to `dfvetest/`

Then, add modules for DF/VE contracts that we don't have yet:
- [ ] DFRewards, in df_rewards.py (and test in dfvetest/)
- [ ] DFStrategyV1, in df_strategy_v1.py (and test)
- [ ] SmartWalletChecker, in smart_wallet_checker.py (and test)
- [ ] veDelegation, in ve_delegation.py (and test)
- [ ] veDelegationProxy, in ve_delegation_proxy.py (and test)
- [ ] veFeeEstimate, in ve_fee_estimate.py (and test)
