### ISSUE TITLE
Improve DX for key-value and profile-NFTs: abstract away erc725 hash, encrypt, decrypt

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1260]
### Background / motivation

The [key-value-flow.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/key-value-flow.md) and [profile-nfts-flow.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/profile-nfts-flow.md) READMEs have super-useful functionality by leveraging ERC725 to the max: on-chain key-value (noSQL) datastore, SBTs, on-chain & private user profiles

To implement this, the READMEs had to do a lot of grunt work
- hash the key everywhere, to make ERC725 happy
- lotsa munging of data to make encryption play well with ERC725 (example below)

Doing this opens up future possibilities:
- trustless datatoken-based data sharing, where data payload is the ERC725. The trick: "make it where it's easy to share with >>1  people by pre-generating keys, with a different url for each datatoken minted"
- trustless data sharing for large data: put data payload into arweave. Leverage pybundlr.

### TODO

- [x] Implement DataNFT set/get without needing user to hash the input key
- [x] Create new crypto.py module to make it easy to do: create symmetric key; symmetric encrypt/decrypt; asymmetric encrypt/decrypt. Test it
- [x] Rename key-value & profile-nft READMEs to be key-value-private/public. Update them to use the new crypto.py library

### Example

Here's step 3 status quo. "Alice adds key-value pair to data NFT. 'value' encrypted with a symmetric key 'symkey'" :
```python
# Key-value pair
profiledata_name = "fav_color"
profiledata_val = "blue"

# Prep key for setter. Contract/ERC725 requires keccak256 hash
profiledata_name_hash = Web3.keccak(text=profiledata_name)

# Choose a symkey where:
# - sharing it unlocks only this field: make unique to this data nft & field
# - only Alice can compute it: make it a function of her private key
# - is hardware wallet friendly: uses Alice's digital signature not private key
preimage = data_nft.address + profiledata_name
preimage = sha256(preimage.encode('utf-8')).hexdigest()
prefix = "\x19Ethereum Signed Message:\n32"
msg = Web3.solidityKeccak(
    ["bytes", "bytes"], [Web3.toBytes(text=prefix), Web3.toBytes(text=preimage)]
)
signed = sign_with_key(msg, alice.private_key)
symkey = b64encode(str(signed).encode('ascii'))[:43] + b'='  # bytes

# Prep value for setter
profiledata_val_encr_hex = Fernet(symkey).encrypt(profiledata_val.encode('utf-8')).hex()

# set
data_nft.setNewData(profiledata_name_hash, profiledata_val_encr_hex, {"from": alice})
```

**Comment by trentmc** [comment]
@calina-c thanks for reviewing, and helping get this over the line wrt CI tests.

Could you do a new ocean.py release please? So that this is available. (Or if you plan to do one in the next few days anyway, that's fine too.)
