### ISSUE TITLE
Blog posts (w videos) on ocean.py for data scientists

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1351]
### Motivation

ocean.py's in far better shape than 6 mos ago. We can help to spread the word via approachable blog posts, that bring potential users to the READMEs

### General approach

For this github issue: have "intro to ocean.py" blog posts. One for each of original 6 READMEs

For a [follow-up issue](https://github.com/oceanprotocol/ocean.py/issues/1417): have advanced blog posts

### TODOs for this issue

T = Trent, V = Veronica

- [x] [T] Generate splash images with DALL-E, create draft 6+6 articles
- [x] Intro 1 - Getting Started with ocean.py, part 1 - intro & install
  - [x] [T] Write draft [link](https://blog.oceanprotocol.com/getting-started-with-ocean-py-part-1-introduction-installation-530295c3d3b4)
  - [x] [V] Do videos: (a) [intro](https://youtu.be/8uZC6PC9PBM) (b) [install](https://youtu.be/mbniGPNHE_M) 
  - [x] [T] Finalize (link videos etc), publish. [Link](https://blog.oceanprotocol.com/getting-started-with-ocean-py-part-1-introduction-installation-530295c3d3b4)
  - [x] [T] Tweet from @trentmc0. [Link](https://twitter.com/trentmc0/status/1630849841403428865)
  - [x] Tweet from @oceanprotocol 
- [x] Intro 2 - local setup
  - [x] [T] Write draft [link](https://blog.oceanprotocol.com/getting-started-with-ocean-py-part-2-set-up-locally-e232dc8d8182)
  - [x] [V] Do video. (SKIP because Win/Mac issues)
  - [x] [T] Finalize, publish. Link=_
  - [x] [T] Tweet from @trentmc0
  - [x] [V for Nick] Tweet from @oceanprotocol 
- [x] Intro 3 - remote setup
  - [x] [T] Write draft [link](https://blog.oceanprotocol.com/getting-started-with-ocean-py-part-4-set-up-remotely-a3cfec47a3fa)
  - [x] [V] Do video. Link=_
  - [x] [T] Finalize (link video etc), publish. Link=_
  - [x] [T] Tweet from @trentmc0
  - [x] [?] Tweet from @oceanprotocol 
- [x] Intro 4 - walkthrough
  - [x] [T] Write draft [link](https://medium.com/@trentmc0/getting-started-with-ocean-py-part-3-local-walkthrough-4807b21083a6)
  - [x] [V] Do video. Link=_
  - [x] [T] Finalize (link video etc), publish. Link=_
  - [x] [T] Tweet from @trentmc0
  - [x] [?] Tweet from @oceanprotocol

**Comment by trentmc** [comment]
Note: folded https://github.com/oceanprotocol/predict-eth/issues/82 into here

**Comment by trentmc** [comment]
I moved the "advanced topics" content into a new github issue. https://github.com/oceanprotocol/ocean.py/issues/1417

Which means we're done _this_ issue. Thanks @graceful-coder for all your help on this!

The new github issue is lower priority for now. Bigger fish to fry.
