### ISSUE TITLE
quickstart fails using pay_for_service(); recent changes broke backwards compatibility

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#141]
**Describe the bug**

In mid Jan I revised the quickstarts to help make them easier to use. They all worked then. 

Today, I decided to see how they do now. Everything went fine until step 7 of the final quickstart flow - the marketplace quickstart. 

**To Reproduce**
1. Go to marketplace quickstart README
2. Go through the steps. It will fail at step 7 with:
```python
>>> order_tx_id = bob_ocean.assets.pay_for_service(
...     quote.amount, quote.data_token_address, asset.did, service.index, fee_receiver, bob_wallet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pay_for_service() missing 1 required positional argument: 'consumer'
```

**Expected behavior**
1. It doesn't fail. I can complete my quickstart.
2. It doesn't break the interface promise of ocean.py

More on (2): this is a breaking change to the ocean.py interface. Obviously this is a big no-no; we should not do breaking changes to the interface unless it's absolutely necessary as part of a bug fix, or we're going to a new version (rare). In this case it's clear that neither were the case.

**More info**

[Here's the file in mid-Jan](https://github.com/oceanprotocol/ocean.py/blob/5e1a29393f4cacc06c38af05f942cb291192a25a/ocean_lib/ocean/ocean_assets.py). Note in `pay_for_service()` that it does not have a parameter `consumer`.

[Here's the status quo file](https://github.com/oceanprotocol/ocean.py/blob/master/ocean_lib/ocean/ocean_assets.py). Note  in `pay_for_service()` that it *does* not have a parameter `consumer`. According to the docstring it's supposed to default to the payer. But it only does that if `None` is specified explicitly specified.
```python
 def pay_for_service(
...
        from_wallet: Wallet,
        consumer: str,
    ) -> str:
        """
...
        :param from_wallet: Wallet instance
        :param consumer: str the address of consumer of the service, defaults to the payer (the `from_wallet` address)
...
        """
...
        if consumer is None:
            consumer = from_wallet.address
...
```
   
The error was introduced in [this commit](https://github.com/oceanprotocol/ocean.py/commit/a6a76dc38685c55c44cdea7d46a3758725e23ae5#diff-b085f9c75f577fac9b35d97d552e9d70b034711f7aab57279bd0cd72412c3446) of Feb 8.

**TODOs to fix this issue**
- [x] Change the quickstart so at least *it's* not broken before the other stuff is done
- [x] Write / ensure there's a unit test to capture behavior when `consumer` is specified and non-`None`. It should pass.
- [x] Write / ensure there's a unit test to capture behavior when `consumer` is specified and `None`. It should pass.
- [x] Write a unit test "C" for when `consumer` is not specified at all. It should fail.
- [x] Fix the bug. Now all three tests should pass. Commit.
- [ ] Deploy new version of ocean.py

**Comment by alexcos20** [comment]
No need to release a new major.
#143 fixes that, providing compatibility for both scenarios (with consumer or without)

**Comment by alexcos20** [comment]
"Write / ensure there's a unit test to capture behavior when consumer is specified and non-None. It should pass"  - that should be caught in Compute tests
"Write / ensure there's a unit test to capture behavior when consumer is specified and None. It should pass." - that should be caught in Market tests

**Comment by trentmc** [comment]
While this was merged, we still need a new version of ocean.py deployed. @calina-c

**Comment by trentmc** [comment]
Has a new version of ocean-lib been deployed for pypi? (See checklist in ticket description)
