### ISSUE TITLE
"Advanced topics" blog posts on ocean.py for data scientists

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#1417]
### Background / motivation

[ocean.py#1351](https://github.com/oceanprotocol/ocean.py/issues/1351) was: "Intro to Ocean" blog posts + videos on ocean.py for data scientists. It's done.

This issue is the follow-up: have blog posts on advanced topics. Possible topics are listed below.

Q: videos? 
A: TBD. Let's decide once we re-prioritize doing this issue.

Q: priority? 
A: balanced with other traction-driving activities. Therefore, as of late Apr 2023, this is _low_ priority --trentmc

### TODOs

(Repeat for each post)

- [ ] Post xxx
  - [ ] Write draft 
  - [ ] (optional) Do video
  - [ ] Finalize (link video etc), publish. Link=_
  - [ ] tweet from @trentmc0
  - [ ] Tweet from @oceanprotocol 
- [ ] Post yyy
  - [ ] Write draft 
  - [ ] (optional) Do video
  - [ ] Finalize (link video etc), publish. Link=_
  - [ ] tweet from @trentmc0
  - [ ] Tweet from @oceanprotocol 
- [ ] Post zzz
  - [ ] Write draft 
  - [ ] (optional) Do video
  - [ ] Finalize (link video etc), publish. Link=_
  - [ ] tweet from @trentmc0
  - [ ] Tweet from @oceanprotocol 
...

### Possible topics

- Trent will adaptively decide which order to publish these. Possibilities listed below

- predict-eth mainx.md (walk through random).  [Pulled from here](https://github.com/oceanprotocol/predict-eth/issues/82)
- predict-eth walk-through 1
- predict-eth walk-through 2
- predict-eth walk-through 3
- C2D flow
- content from walkthrough README's appendix
- Use-case flow: Data Farming - curate data assets, earn rewards
- Use-case flow:Search & filter data - find assets by tag
- key-value store: public data, then private data
- REST API
- GraphQL
- on-chain data
- Understand config parameters - envvars vs files
- Learn about off-chain services - Ocean Provider for data services, Aquarius metadata store

**Comment by trentmc** [comment]
Not gonna happen, bigger fish to fry
