### ISSUE TITLE
Improve unit and integration testing

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#149]
**Is your feature request related to a problem? Please describe.**
The goal of this epic is to make unit tests and integration tests more thorough, aiming at 95% coverage.
ocean.py is getting a lot of silly bugs that should never happen, things that would be covered if we had thorough unit tests on all the sub-modules.

We have nice, thorough unit tests for `ocean_lib/modules` we have the `tests/models/` directory holding `test_bpool.py`, `test_btoken.py`, etc.

By comparison, for *all* the other functionality combined we only have a single directory `tests/ocean` and one file for each sub-module, such as `test_ocean_assets.py` (which is just 141 lines long).

**Describe the solution you'd like**

Use a more scalable directories setup. That is: Have '/test' directories as subdirectories of each respective module; move tests for existing submodules from './tests'  (This is the standard pytest way when you have more tests. [This commit](https://github.com/oceanprotocol/ocean.py/commit/39f8a92b9b30defb2bacc2788c63a08d4afd455e) (work for #95) is the starting point. The `tokenspice2` repo has more examples yet.) Use './tests' directory for system / integration tests.

We'll probably find 10 or more bugs *proactively* which is 10x more efficient than after-the-fact.

TODOs:
- [x] Move directory `./tests/models/` to `./ocean_lib/models/tests` and make it work
- [x] Move test file `./tests/web3_internal/test_wallet.py` into `./ocean_lib/web3_internal/test` directory and make sure runs & passes; deprecate `./tests/web3_internal` directory
- [x] For each test file in `./tests/ocean`: move it into an appropriate new test directory, as a sub-subdirectory of `./ocean_lib/..`. Make sure it runs & passes. Exception: anything that's more of an integration test can stay here. (If not sure, bias to things in sub-directories imo.)
- [x] Make sure each module (*.py file) has a corresponding test file in proper location (/test subdirectory)
- [x] Make sure each module has happy-path tests for each of its methods
- [x] Add unhappy-path tests. Ideally super-thorough, but trade this off with maintainability.
- [x] Add more tests until code coverage >95%
