### ISSUE TITLE
Epic: Build ocean-lib-py datatokens alpha

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#2]
Phase1 specs high level:
- [x] Functionality: quickstart READMEs for simple flow & marketplace flow at L2 py/js level
- NOT yet “everything guaranteed end-to-end for L3 marketplace”. Including: ok if DT transfer is done manually from Alice to Bob
- NOT yet compute-to-data
- [x] 75% coverage in unit tests. (Can leverage squid tests)
- [x] At least one integration tests using Rinkeby
- [x] Network selector based on short names
- Alpha quality
