### ISSUE TITLE
Non-blocking nature of calls hurts DX/maintenance. So, use blocking

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#227]
**Problem**
In debugging issue #185 and #205, I would have found errors sooner if it was clear that the tx did not go through. For those: there was a call to create a datatoken, but the tx did not work.

In other cases, the tx may work but there could be non-negligible network latency until the tx goes through.

The general challenge: the developer needs to muck around to know if the tx is done, whether successful or not.

**Proposed Solution**
We can make it better: make the calls _blocking_. That is, wait until the tx has completed. If it doesn't complete or fails, return an error or None. Otherwise simply keep going. Do it in `contract_base.py::send_transaction()`, using `is_tx_successful()`.

This will make the DX better because it abstracts away all network-y stuff for ocean.py users. 

It also helps ocean.py maintainability.

**TODOs**

- [x] first cut implement
- [x] ask: is it addressing when a tx fails? And are there unit tests on this? if not, fix
- [x] ask: is it addressing when gas is super-low and tx hangs indefinetely? And are there unit tests on this? If not, fix. ocean.js addresses by having a timeout of 10 min.
- [x] get all pytest / tox tests working locally
- [x] update READMEs
- [x] test on rinkeby or ropsten
- [ ] test on eth mainnet
- [x] test on polygon 
- [x] test with "import ocean_lib". Including on rinkeby or ropsten, eth mainnet, and polygon. Why: may cause weird things here too
- [ ] commit PR to main
- [ ] create a new release

**Comment by trentmc** [comment]
Put into V4 since this changes behavior.

**Comment by DMats** [comment]
I've decided to test this issue using a slightly modified version of the `marketplace-flow.md`. 

I marked it blocked here: https://github.com/oceanprotocol/ocean.py/issues/227#event-4911179119 because I observed errors that were likely caused by aquarius. At the time, I was testing with the "main" aquarius endpoints.

It was determined at today's sprint planning meeting that I should test this with the deployed "stable-aqua" aquarius endpoints instead of the "main" aquarius endpoints because the `stable-aqua` branch will be merged to `main` very soon. The team believes that tests performed now will still be valid after the merge.

**Comment by trentmc** [comment]
I was just reviewing the main PR for this issue: https://github.com/oceanprotocol/ocean.py/pull/288

The heart of the PR should do blocking: there should be have a loop that repeats until the tx has gone through (or some timeout). It would be in ocean_lib/web3_internal/contract_base.py::send_transaction()
- Here's that part of the PR: https://github.com/oceanprotocol/ocean.py/pull/288/files#diff-178d93ac62ac1716096d4321ff14bb9897f3996a223174c3784d91c346a8c6cd
- But, there is no loop added. All it does is check if the tx was successful, and if not, returns "not successful"

Therefore this issue was _not_ completed. It really shouldn't have been closed. 

Fortunately, another ticket has already picked up on this: "Add block confirmations" #393. It basically says "do blocking" including x confirmations. Therefore _this_ ticket can stay closed and that one is picking up where this one left off. Also, work for that ticket has already added a blocking loop like I had expected here. Details:
-Key method is web3_internal/web3_overrides/utils.py::wait_for_transaction_receipt_and_block_confirmations()
-[Code Link](https://github.com/oceanprotocol/ocean.py/blob/2560fca890dbbf34a65cfbde25de754814407829/ocean_lib/web3_internal/web3_overrides/utils.py)
-Code snippet:
```python
def wait_for_transaction_receipt_and_block_confirmations(
    web3: Web3,
    tx_hash: HexBytes,
    block_confirmations: int,
    block_number_poll_interval: float,
    timeout: int = 120,
) -> TxReceipt:
    """Wait for the transaction receipt. Then, verify the transaction receipt
    still appears in the chain after `block_confirmations` number of blocks.
    Return the transaction receipt.
    :param web3: Web3, used to query for transaction receipts and block number.
    :param tx_hash: HexBytes, the transaction hash.
    :param block_confirmations: int, larger number of block confirmations
      increases certainty that transaction has settled.
    :param block_number_poll_interval: interval
    :param timeout: Optional[int], amount of time to wait for initial tx receipt
      in seconds.
    """
    receipt = web3.eth.wait_for_transaction_receipt(tx_hash, timeout)
    while web3.eth.block_number < receipt.blockNumber + block_confirmations:
        time.sleep(block_number_poll_interval)
    return web3.eth.get_transaction_receipt(tx_hash)
```

Summary:
- this issue was not completed, we should not have closed it
- fortunately #393 picked up from this and is on track to properly complete _this_ issue too
