### ISSUE TITLE
Deprecate creating fake OCEAN from within ocean.py

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#278]
**Is your feature request related to a problem? Please describe.**

In ocean.py for marketplace README quickstart, we generate fake OCEAN as explicit step. Most recently for #200.

Alex mentioned late last week that now ocean contracts repo generates fake OCEAN, and then it shows up in barge. If this is truly the case then we don't need the explicit step in OCEAN.

**Describe the solution you'd like**
Deprecate creating fake OCEAN from within ocean.py

Make sure it works in the marketplace README.

**TODOs**

- [x] Revive Calina's PR
- [ ] test the PR, fix as needed
- [ ] commit PR to main
- [ ] new ocean_lib release to pypi
- [ ] test "import ocean_lib" in marketplace README, does it work?

~~Notes: fixing this will unblock #201 - SQL alchemy. PR #276~~ (That issue is deprecated, don't need)
