### ISSUE TITLE
Ocean.py support V4 smart contracts

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/ocean.py#357]
Background: v4 smart contracts are built (alpha form). They include js unit tests inside the contracts repo.

Next up: update ocean.js and ocean.py to support the new functionality.

Context:
- [V4 super-epic](https://github.com/oceanprotocol/multi-repo-issue/issues/93)
- Blog posts on ERC721 + ERC20 for IP. First of three [here](https://blog.oceanprotocol.com/nfts-ip-1-practical-connections-of-erc721-with-intellectual-property-dc216aaf005d)

TODOs for this issue:
- [ ] get ocean.py to support each of 
  - [ ] NFT-ize base IP in contracts & ocean.js
  - [ ] Updated metadata
  - [ ] Arch for >1 DT type
  - [ ] Diff't revenue account than publisher
  - [ ] Help community monetize
  - [ ] Whatever else is needed
- [ ] update ocean.py README for one or more new flows
- [ ] update docs
