### ISSUE TITLE
Specifying which network to use is unclear / inconsistent, and parameters.md is out of date

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#523]
**Describe the bug**

Since its inception, ocean.py's key way to set config vars has been: "We can set any config parameter (a) via an envvar, or (b) via a config file. Envvar values override config file values." Details in [READMEs/parameters.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/parameters.md)

Matthias and I were recently iterating around a press release for a new network. It had a couple lines on how developers might specify the network for ocean.py. 
- Matthias had legitimate remarks: what specific parameter is set? What specific value? "Just set the RPC".  
- So I went into the code and looked around. It's changed a lot recently!

What I found: In `example_config.py::ExampleConfig::get_config()` , the first line is `network_url = os.getenv("OCEAN_NETWORK_URL")`. So it's always grabbing an envvar! 

This is inconsistent with the rule on config vars that we've been following forever, as specified in `READMEs/parameters.md`. 

And: What if I wanted to specify the network url by code, not via an envvar? I should be able to. I think it's still possible, but it's no longer so obvious.

To generalize, it looks like [READMEs/parameters.md](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/parameters.md) hasn't been updated to reflect recent changes. It's become inconsistent with the code

Also weird: `example_config.py` seems to have a lot more than an example! It seems to have all the networks' URIs (for provider, aquarius, network name). These are essentially constants. It's strange to put constants into an _example_ config file.

**TODOs*

- [ ] Ensure that code and READMEs follow rule "We can set any config parameter (a) via an envvar, or (b) via a config file. Envvar values override config file values."
- [ ] Consistency among (a) actual code (b) READMEs/parameters.md (c) quickstart READMEs
- [ ] Constants are not in "example" config file, but a better place

**Notes**

@DMats had already been working on some of this in [this PR](https://github.com/oceanprotocol/ocean.py/pull/511). 
- I'm attaching that PR to this issue: all PRs should have an issue! 
- That PR doesn't do cover all the TODOs of this issue.
- That PR had been put on hold for V4. However that was before these issues were flagged as a bug - it's a real problem if a dev wants to use any network! So we need to reconsider doing it sooner.

**Comment by trentmc** [comment]
@DMats please focus on Provider

**Comment by AnaLoznianu** [comment]
Closing this, as is related to the V3 ocean.py version and now we have the V4.
