### ISSUE TITLE
Update/deprecate READMEs (not flow related) for v4

### ISSUE THREAD

**Issue by calina-c** [oceanprotocol/ocean.py#743]
**Motivation**

All of ocean.py READMEs should be up-to-date according to v4.

**TODOs**

For each of the following: review it, then either update or deprecate. (If deprecate, remove from top-level README.md too of course.)

- [x] [Get test OCEAN](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/get-test-OCEAN.md) 
- [x] [Understand config parameters](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/parameters.md) 
- [x]  [Learn about off-chain services](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/services.md) 
- [x] [Learn about wallets](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/wallets.md) 
- [x] [Developers flow](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/developers.md) 
- [x] [Release process](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/release-process.md)

Deleted:
- [x] [Learn about the structures we use for ABI matching](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/structures.md) 
- [x] [Get an overview of ocean.py](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/overview.md)
- [x] [Testing v4](https://github.com/oceanprotocol/ocean.py/blob/v4main/READMEs/testing-v4.md)

**Comment by mariacarmina** [comment]
Testing v4 should be removed, it was an intermediary README.
