### ISSUE TITLE
Epic: compute-to-data example & trusted algs

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#8]
Target output of this epic: 

1. a README:
- [x] Compute-to-data example README "make it work" -- ocean.py #101 -- Alex
- [ ] Compute-to-data example README "make it good" -- ocean.py #279 -- Trent. Depends on previous.

2. Algorithms in Ocean Market
- [x] Compute-to-data example in Ocean Market -- [multi-repo-issue#63](https://github.com/oceanprotocol/multi-repo-issue/issues/63) -- Alex
- [ ] Publish common algorithms (in Ocean Market) that publishers can easily add as trusted in compute assets -- [market#382](https://github.com/oceanprotocol/market/issues/382) -- Trent. Depends on previous.

Bonus (but maybe do via contractors)
- [ ] Wrote a blog post about the above

**Comment by Akif-G** [comment]
@trentmc 
https://github.com/oceanprotocol/datascience-scripts gives 404 right now. datascience-scripts repo is deprecated.

**Comment by trentmc** [comment]
> https://github.com/oceanprotocol/datascience-scripts gives 404 right now. datascience-scripts repo is deprecated.

And that's fine. They weren't needed and aren't needed here. All we need is a single new README like #101 discusses.

**Comment by trentmc** [comment]
There's no need to have this as an epic. The two remaining issues can be handled standalone. Therefore closing this.
