### ISSUE TITLE
Readmes on key-value db, profile NFTs, messaging data NFTs 

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#801]
**Motivation**

1. **Key-value db.** Data NFTs can store arbitrary key-value pairs on-chain. This opens up their usage for a broad variety of applications, such as comments & ratings, attestations, and privately sharing data (when the value is encrypted).
2. **Profile NFT.** Data NFTs can store data encrypted on-chain. It could store personal data ("personal data NFT"). It could securely share user profile data with dapps ("profile NFT"), for a "Login with Web3" flow.
3. **Message NFT.** People can also use Data NFTs to message others. We could (a): have a global message bus for all messages via the key-value store ("message-bus NFT"). Or, have (b) each message gets its own data NFT ("message NFT").

**TODOs in this issue**
- [x] Play around with the above ideas in a README context
- [x] write (1) into a README, if it works out
- [x] write (2) into a README, if it works out
- [x] write (3) into a README, if it works out. Note: this is included in (2) where Alice uses the NFT to send a message to the Dapp.

PR was [here](https://github.com/oceanprotocol/ocean.py/pull/802).

**Comment by trentmc** [comment]
@AnaLoznianu what's the context to reopen this, please? 
cc @calina-c

**Comment by AnaLoznianu** [comment]
@trentmc I think I did some changes to an outdated version. Closing it
