### ISSUE TITLE
ocean.py v2: use Brownie

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#977]
### Motivation

Right now ocean.py directly uses web3.py to interact with chains. It has tons of boilerplate code to expose Ocean smart contract functionality, to handle events, and to expose other web3 functionality. Often, when an issue in EVM or Solidity occurs, it gets hidden by ocean.py. For example, [#943](https://github.com/oceanprotocol/ocean.py/issues/943) reports an error where  ocean.py thinks it's a list error, but it's actually a problem smart contract addresses; ocean.py's 5 layers in between have obfuscated this and signficantly hurt debuggability. 

### A Tool Towards a Solution

However there's also eth-brownie. Via brownie: each smart contract becomes a Python class, and each deployed smart contract becomes a Python object. Therefore all Solidity methods get exposed, cleanly, as Python methods. Events are much easier to work with. With brownie directly we can even have a Python console to Solidity (!). We use Brownie in df-py and tokenspice, to great benefit.

### Proposed Solution, and Benefits

Aim of this issue: put brownie into the core of Ocean.py. Call it "ocean.py v2"

Benefits to ocean.py: simpler (30-60% less code), more maintainable (because less code), yet more functionality (because Solidity functionality is directly exposed).

### How

Candidate approaches:

1. Branch ocean.py, rip out the core contracts stuff and replace with brownie. 
2. Start a completely new repo, with brownie at the core, and layer the rest in (Aquarius, Provider)

Analysis: 
(2) theoretically will result in something with cleaner foundation. But it's risky: I worry about "second system syndrome" where a shiny silver bullet ends up taking way longer than anticipated. Yet (1) needs to navigate a bunch of existing complexity. But, incremental refactoring is always more powerful than we like to give credit for. 

### TODO for this issue

- [ ] First, do a quick 3 day tech spike for (2). 
- [ ] Then, decide after that: continue (2) or try a tech spike for (1). Decide after  few days the final approach. 
- [ ] Do the rest (is the bulk of the work)

**Comment by calina-c** [comment]
I am closing a duplicate (#1019) and I'm moving everything still relevant onto here.

Pending technical TODOs:
- [ ] reinstate enforce types where needed (possibly we should keep it more lax to map to brownie?)
- [ ] remove currency functions

Also pending:
- [ ] testing ocean.py by our team, making sure I didn't miss anything critical

**Comment by calina-c** [comment]
@trentmc @AnaLoznianu I created the follow-up issues and tagged them in my previous comment. I think we can close this ticket after we rename the main-brownie branch.
